TootSDK/TootSDK

README.md

fix: url to documentation website

---

Examples/swiftui-toot/SwiftUI-Toot.xcodeproj/project.pbxproj
Examples/swiftui-toot/TootSDK-Demo/TootSDK_DemoApp.swift
Examples/swiftui-toot/TootSDK-Demo/Views/Feed/FeedSelectionView.swift
Examples/swiftui-toot/TootSDK-Demo/Views/Feed/FeedView.swift
Examples/swiftui-toot/TootSDK-Demo/Views/Feed/FeedViewModel.swift
Sources/TootSDK/TootClient/TootClient+TimeLine.swift
Sources/TootSDK/TootStream.swift

This PR:
* Fixes our streaming function so that it updates the PageInfo object with the latest results from the API. This means each successive refresh will retrieve only new data.
* Adds Local and Federated timelines GET calls
* Updates the SwiftUI demo app so that it has a segmented picker to switch between home/local/federated timelines

Updated Stream paging + add local/federated calls

---

Sources/TootSDK/TootStream.swift

This is a 1-liner fix; we have just never been using the PageInfo provided, to TootStream 🤦 
This addresses #92

Fix - Use the pageInfo in TootStream when first setting up the stream

---

Examples/swiftui-toot/SwiftUI-Toot.xcodeproj/project.pbxproj
Examples/swiftui-toot/SwiftUI-Toot.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

nuke has no branch named master so a package reset and subsequent updates break also updated the revision of EmojiText while testing the package update

changed branch of nuke from master to main

---

.github/workflows/build.yml
.github/workflows/build_examples.yml
Examples/swiftui-toot/SwiftUI-Toot.xcodeproj/project.pbxproj
Examples/swiftui-toot/SwiftUI-Toot.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
README.md

* fix broken link in README 
* SwiftUI Example: allow Nuke dependency to next major version
* SwiftUI Example: upgrade EmojiText and use versioned dependency, fixes #96 
* Add macOS to the build matrix
* Ignore certain paths from triggering a full rebuild

Improvements to docs, build pipeline and SwiftUI examples

---

Sources/TootSDK/Models/UpdateMediaAttachmentParams.swift
Sources/TootSDK/TootClient/TootClient+Media.swift

https://docs.joinmastodon.org/methods/media/#update
https://api.pleroma.social/#operation/MediaController.update
Because mime type is only necessary when updating thumbnail I decided to provide 2 separate initializers for params. First skips thumbnail and second makes it required together with mime type. It might be more inconvenient if someone would want to update thumbnail only conditionally, but we are preventing situation where someone passes it without mime type.

API to update media attachment

---

Sources/TootSDK/Models/MediaAttachment.swift

Encountered post that has missing `y` coordinate: https://darkfriend.social/@hybridhavoc/110027606492965987

Make attachment meta focus coordinates optional

---

Sources/TootSDK/TootClient/TootClient+Post.swift

Code should never return nil (either returns Post or throws) so make it consistent with the other functions like boost.
https://github.com/TootSDK/TootSDK/discussions/124

delete/favourite/unfavouritePost return Post instead of Post?

---

Sources/TootSDK/Models/List.swift

repliesPolicy had the same comment as title, replaced it with the doc from the Mastodon API spec
Also removed an extra space in ListRepliesPolicy comments.

Comment fix in List.swift

---

Examples/swiftui-toot/SwiftUI-Toot-Info.plist
Examples/swiftui-toot/SwiftUI-Toot.xcodeproj/project.pbxproj

When running the SwiftuUI-Toot example, the Xcode console shows this warning right in the beginning:
Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
The warning is removed by adding a UISceneConfigurations key to info.plist as described here:
https://stackoverflow.com/questions/74805019/info-plist-contained-no-uiscene-configuration-dictionary-looking-for-configurat
Note that the parent UIApplicationSceneManifest key and UIApplicationSupportsMultipleScenes sibling key are already visible in the Xcode info display but show up in info.plist after adding the UISceneConfigurations key.

fix "no UISCene configuration directory" warning

---

Sources/TootSDK/TootStream/TootStream+Posts.swift

Fixes issue with minId being set to nil when no content is returned

---

Sources/TootSDK/TootClient/TootClient+Lists.swift

consistent with addAccountsToList and RemoveAccountsFromListParams
https://github.com/TootSDK/TootSDK/discussions/138

removeAccountsFromAList -> removeAccountsFromList

---

Sources/TootSDK/Models/Emoji.swift
Sources/TootSDK/Models/PostEdit.swift

Seems like many or most of the TootSDK models implement Hashable, but PostEdit doesn't and in this case I need PostEdit to be Hashable to pass to a custom NavigationStack path like this:
```swift
enum Route : Hashable {
case postDetail(Post)
case postEdit(PostEdit)
case profile(Account)
case reply(Post)
}
```

PostEdit implements Hashable

---

Sources/TootSDK/Models/TootSDKFlavour.swift

While working on #144 I discovered that the Friendica API documentation linked from `TootSDKFlavour` is outdated and [the documentation in their GitHub repo](https://github.com/friendica/friendica/blob/stable/doc/API-Mastodon.md) is up to date for the stable version. This PR updates the link.

Up to date Friendica documentation link

---

Sources/TootSDK/TootClient/TootClient+Account.swift
Sources/TootSDK/TootClient/TootClient+Lists.swift
Sources/TootSDK/TootClient/TootClient+Notifications.swift
Sources/TootSDK/TootClient/TootClient+Relationships.swift
Sources/TootSDK/TootClient/TootClient+Tags.swift
Sources/TootSDK/TootClient/TootClient+TimeLine.swift
Sources/TootSDK/TootClient/TootClient.swift

added TootClient.fetchPagedResult(req) called by all the functions that return PagedResult.
It's basically the same as getPosts (which I changed to call this new function), but with a generic type (specified as Decodable, but that can be omitted, the type inference handles it).

cleanup: refactor fetch of paged result into a shared function

---

Package.resolved
Sources/TootSDK/TootClient/TootClient+Account.swift
Sources/TootSDK/TootClient/TootClient+Suggestions.swift
Sources/TootSDK/TootClient/TootClient+Tags.swift

Added TootClient.removeSuggestion which accesses this API
https://docs.joinmastodon.org/methods/suggestions/#remove
I tested this on universeodon.com and it works, but apparently only on suggestions with a past_interactions source (which isn't documented but kind of makes sense, that's the only suggestion type that is tailored to the user)

add removeSuggestion

---

Sources/TootSDK/HTTP/Pagination.swift
Sources/TootSDK/Models/PushSubscription.swift
Sources/TootSDK/TootClient/TootClient+Notifications.swift
Tests/TootSDKTests/PaginationTests.swift

* [all platforms] Adds the `reblog` alert from the push notification request.
* [all platforms] Removes the identifier from `PushSubscription` (which is unused for API calls) as it requires special handling because it can be a `String` (Pleroma/Akkoma) or an `Int` (Mastodon) depending on server type.
* [all platforms] Enhances pagination to tolerate spaces and line breaks before or after pagination header values (Pleroma/Akkoma seems to produce them sometimes when paginating notifications).
* [Linux] Pagination link parsing now uses [WebURL](https://github.com/karwa/swift-url) to offer consistent validation across platforms. (cf. [see here](https://github.com/TootSDK/TootSDK/pull/167#issuecomment-1554916164))

Improve compatibility for web push notifications and pagination

---

Package.resolved
Sources/TootSDK/Models/ProfileDirectoryParams.swift
Sources/TootSDK/TootClient/TootClient+Notifications.swift
Sources/TootSDK/TootClient/TootClient+ProfileDirectory.swift
Sources/TootSDK/TootClient/TootClient+ScheduledPost.swift

Added TootClient.getProfileDirectory to access the Mastodon directory API.
Added a paged version of TootClient.getScheduledPosts (can probably replace the array-returning getScheduledPost)
Added parameter doc for limit in TootClient.getNotifications
Updated swift-nio package via Get Latest Packages in Xcode.
Sample result from getProfileDirectory

added getProfileDirectory, getScheduledPosts

---

Sources/TootSDK/Models/FeatureTagParams.swift
Sources/TootSDK/Models/FeaturedTag.swift
Sources/TootSDK/TootClient/TootClient+Account.swift
Sources/TootSDK/TootClient/TootClient+FeaturedTags.swift

Added TootClient functions to access the Mastodon featured_tags API for featuring/unfeaturing tags, and viewing and suggesting featured tags.
https://docs.joinmastodon.org/methods/featured_tags/
Placed them in TootClient+FeaturedTags.swift and moved the existing getFeaturedTags (that takes an account ID) there.

feat: featured_tags API

---

Examples/swiftui-toot/SwiftUI-Toot.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift
Sources/TootSDK/Extensions/Decoding+Helpers.swift
Sources/TootSDK/Models/FeaturedTag.swift
Sources/TootSDK/Models/ScheduledPost.swift
Sources/TootSDK/Models/ScheduledPostParams.swift
Sources/TootSDK/Models/ScheduledPostRequest.swift
Tests/TootSDKTests/PostTests.swift
Tests/TootSDKTests/Resources/scheduled_post_attachment.json
Tests/TootSDKTests/Resources/scheduled_post_reply.json
Tests/TootSDKTests/Resources/scheduled_post_sensitive.json

Scheduling a post with a content warning was breaking reading of scheduled posts because the sensitive flag was returned as a string instead of bool. Workaround is to have a custom decoder that calls decodeFromBool (patterned after the existing decodeFromInt).
Other misc stuff: fix comment doc for scheduledAt, make ScheduledPost Hashable (so it can be passed in routes), and update packages, specifically swift-nio.

workaround for ScheduledPost.sensitive returning as string instead of bool

---

Sources/TootSDK/Models/Relationship.swift
Sources/TootSDK/Models/ScheduledPostParams.swift
Sources/TootSDK/TootClient/TootClient+Account.swift
Sources/TootSDK/TootClient/TootClient+Relationships.swift

added TootClient.pinAccount, TootClient.unpinAccount, and TootClient.getEndorsements
https://docs.joinmastodon.org/methods/endorsements/
Also filled in some of the param doc in TootClient+Relationship.swift and added some clarifying doc for ScheduledPostParams in relation to ScheduledPost and ScheduledPostRequest.

feat: access to endorsements API

---

Sources/TootSDK/Models/TootFeature.swift
Sources/TootSDK/TootClient/TootClient+FeaturedTags.swift
Sources/TootSDK/TootClient/TootClient+Tags.swift
Sources/TootSDK/TootClient/TootClient.swift
Tests/TootSDKTests/FeatureTests.swift

This pull request builds upon #187. Now that there are more features that I would like to check if are supported I decided to unify the api.
- Added a new `TootFeature` feature that describes requirements for a feature. Right now it has a list of supported flavours but could be extended to other requirements in future.
- Added requireFeature internal method that can be used to perform runtime check where necessary
- Use this new API to add featured tags and hashtag following features.
- This is a breaking change as it removes previously used `canXXX` variables. If necessary this removal can be reversed to preserve API compatibility.
Possibly related to #27.

API to represent features and check if they are supported

---

Sources/TootSDK/Models/Instance.swift
Sources/TootSDK/Models/InstanceRule.swift
Sources/TootSDK/TootClient/TootClient+Instance.swift

- Parse instance rules from instance info (https://docs.joinmastodon.org/entities/Instance/#rules) when using `TootClient.getInstanceInfo()`
- Ability to request just the rules from [`api/v1/instance/rules`](https://docs.joinmastodon.org/methods/instance/#rules) using `TootClient.getInstanceRules()`

Add support for instance rules

---

Sources/TootSDK/Models/PixelfedReportParams.swift
Sources/TootSDK/Models/ReportCategory.swift
Sources/TootSDK/Models/ReportParams.swift
Sources/TootSDK/TootClient/TootClient+Reports.swift

All flavours except for Pixelfed use:
- https://docs.joinmastodon.org/methods/reports/#post
Pixelfed doesn't implement that API but has its own. Unfortunately I didn't find public documentation so this implementation is based on source code.
- [Endpoint route](https://github.com/pixelfed/pixelfed/blob/4b9d0dc6efb1206ac51fc00e6f94c264da33d278/routes/api.php#L114)
- [Endpoint implementation](https://github.com/pixelfed/pixelfed/blob/4b9d0dc6efb1206ac51fc00e6f94c264da33d278/app/Http/Controllers/Api/ApiV1Dot1Controller.php#L68)
- Example from Vernissage (open source Pixelfed iOS app): [Reports.swift](https://github.com/VernissageApp/Vernissage/blob/2b88870995366de53ac99b250f68e2f928e5482b/PixelfedKit/Sources/PixelfedKit/Targets/Reports.swift#L15), …

Add support for reports

---

Sources/TootSDK/Models/Poll.swift

Why:
- Allow SDK users to create mock data for use with SwiftUI #Preview.
Notes:
- Currently, this would involve decoding a mock JSON payload containing Poll data, which is considerably more work than writing some mock data in Swift.

Add public init to Poll.Option

---

Sources/TootSDK/Models/Announcement.swift
Sources/TootSDK/TootClient/TootClient+Announcements.swift

The additional fields include emojis and emoji reactions, as shown in this screenshot of the announcement on mstdn.social. Also made Announcement.read optional per the mastodon spec.
https://docs.joinmastodon.org/entities/Announcement/#read

fill in missing fields in Announcement and add TootClient.addAnnouncementReaction, TootClient.removeAnnouncementReaction

---

Package.swift
Sources/TootSDK/Models/Instance.swift
Tests/TootSDKTests/InstanceTests.swift
Tests/TootSDKTests/Resources/instance_friendica_nocontact.json

Added a decoder for Instance, handles the case of Friendica (example cambrian.social) returning [] instead of nil for no contact account, resulting in this error
```
[TootSDK bug] There was an error decoding incoming data:
Type 'Dictionary<String, Any>' mismatch:Expected to decode Dictionary<String, Any> but found an array instead.
codingPath:[CodingKeys(stringValue: "contactAccount", intValue: nil)].
```

fix: handle Friendica returning [] instead of nil for contact account

---

Examples/swiftyadmin/Sources/swiftyadmin/Notifications/DeletePushSubscription.swift
Examples/swiftyadmin/Sources/swiftyadmin/Notifications/GetPushSubscription.swift
Examples/swiftyadmin/Sources/swiftyadmin/Notifications/ListAllNotifications.swift
Sources/TootSDK/Models/Alerts.swift
Sources/TootSDK/Models/PushSubscription.swift
Sources/TootSDK/Models/PushSubscriptionParams.swift
Sources/TootSDK/Models/PushSubscriptionPolicy.swift
Sources/TootSDK/Models/PushSubscriptionUpdateParams.swift
Sources/TootSDK/Models/TootNotification.swift
Sources/TootSDK/Models/TootNotificationParams.swift
Sources/TootSDK/TootClient/TootClient+Notifications.swift
Tests/TootSDKTests/TootNotificationParamsTests.swift

This pull request introduces lots of changes related to notifications and push notifications API. Needed to correctly implement notifications support across all available flavours in SDK.
- Added option to configure `update` notification alert in init
- Added optional `policy` to push subscription response
- Changed `policy` to enum with known values
- Added `static NotificationType.supported(by:)`, `NotificationType.isSupported(by:)` to determine if given flavour supports selected notification type
- Added `static NotificationType.supportedAsPush(by:)`, `NotificationType.isSupportedAsPush(by:)` to determine if given flavour supports selected notification type in push subscriptions
- Added mapping from `types` to `excludeTypes` for Friendica which doesn't support the former
- Fixed akkoma …

Notifications API improvements

---

Examples/swiftyadmin/Package.resolved
Examples/swiftyadmin/Sources/swiftyadmin/Account/FollowAccount.swift
Examples/swiftyadmin/Sources/swiftyadmin/swiftyadmin.swift
Sources/TootSDK/Models/FollowAccountParams.swift

With this change it will be possible to update account following parameters one by one. For example to be able to enable account notifications without changing boosts following status.
Default values are set to `nil` to follow server preferences.

Add follow-account example command

---

README.md

This is just to get started, with tootsdk apps that I have on my own list and added to the awesome-mastodon list (they have a format that includes several links for each app but for this I just picked what seemed like the main link for each).
I'm sure I've seen a bunch of these built-with lists on other projects, for example SDWebImage has one on a separate page (but they have a lot of users)
https://github.com/SDWebImage/SDWebImage/wiki/Who-Uses-SDWebImage

added a list of apps built with TootSDK to the README

---

Package.swift
Sources/TootSDK/Models/ExtendedDescription.swift
Sources/TootSDK/Models/Instance.swift
Tests/TootSDKTests/FlavourTests.swift
Tests/TootSDKTests/Resources/instance_catodon_contact_removed.json

so you can instantiate with
ExtendedDescripion()
vs
ExtendedDescription(content: "")
edit: catodon.social updated today with code newly synced to iceshrimp but with catodon added to the version string, so updated the TootSDK flavour check accordingly

add default empty string param for ExtendedDescription

---

README.md

Hey, thanks to TootSDK, I was able to build TootLater, an iOS/Mac app for scheduling Mastodon posts, and I just released it.

Add TootLater to list of apps

---

Sources/TootSDK/Models/ReportCategory.swift

This report category isn’t in Mastodon’s docs yet, but was added in mastodon/mastodon#23941 and released in Mastodon 4.2.0.

Support Mastodon's `legal` category for reporting illegal content

---

Sources/TootSDK/Models/InstanceRule.swift

This is another thing that was recently added to Mastodon (mastodon/mastodon#29539) but not officially released or documented yet (although mastodon.social and mastodon.online already have it deployed).
This one shouldn’t have any impact on usage with servers that don’t support it, because it’s optional.

Add support for `hint` property on `InstanceRule`

---

Sources/TootSDK/Models/List.swift
Sources/TootSDK/Models/ListParams.swift
Tests/TootSDKTests/ListTests.swift

Added in Mastodon 4.2 (exclusive property already present in the List test case)
https://docs.joinmastodon.org/methods/lists/#create

Allow setting a list as "exclusive"

---

Sources/TootSDK/Models/Account.swift
Tests/TootSDKTests/AccountTests.swift

Available since Mastodon 3.2.0, added in the code relative to other properties in the same location as listed in the API doc:
https://docs.joinmastodon.org/entities/Account/#group

Added Account.group

---

Sources/TootSDK/Models/RelationshipParams.swift
Sources/TootSDK/TootClient/TootClient+Relationships.swift

Introduced in Mastodon 4.3.0
https://docs.joinmastodon.org/methods/accounts/#relationships
Passed via a RelationshipParams struct in the same manner as params in getAnnouncements (and others).

added optional withSuspended param to TootClient.getRelationships (specifies whether to ignore suspended accounts)

---

Sources/TootSDK/Models/Card.swift

Adds optional `blurhash` property to `Card` (link preview card). Also adds documentation to `Card` properties based on the Mastodon documentation.

Support blurhash on preview cards

---

Package.swift
Sources/TootSDK/Models/NodeInfo.swift
Sources/TootSDK/Models/TootNotification.swift
Sources/TootSDK/Models/TootSDKFlavour.swift
Sources/TootSDK/TootClient/TootClient+Account.swift
Sources/TootSDK/TootClient/TootClient+Conversation.swift
Sources/TootSDK/TootClient/TootClient+DomainBlocks.swift
Sources/TootSDK/TootClient/TootClient+FeaturedTags.swift
Sources/TootSDK/TootClient/TootClient+Filters.swift
Sources/TootSDK/TootClient/TootClient+FollowRequests.swift
Sources/TootSDK/TootClient/TootClient+Lists.swift
Sources/TootSDK/TootClient/TootClient+Markers.swift
Sources/TootSDK/TootClient/TootClient+Post.swift
Sources/TootSDK/TootClient/TootClient+Relationships.swift
Sources/TootSDK/TootClient/TootClient+Streaming.swift
Tests/TootSDKTests/FlavourTests.swift
Tests/TootSDKTests/Resources/nodeinfo_gotosocial.json

`domainBlocks` feature was split to `adminDomainBlocks` since only this part is supported by GoToSocial.
Closes #287

GoToSocial flavour

---

Sources/TootSDK/Models/PostEdit.swift

Fixes for post edits history endpoint model which was incorrect.
Post history doesn't return full poll model. Instead it only returns poll options. Additionally date is always present.
https://docs.joinmastodon.org/entities/StatusEdit/#poll

Fix post edit model

---

Sources/TootSDK/HTMLRendering/TootHTML.swift
Tests/TootSDKTests/AttribStringRendererTests.swift
Tests/TootSDKTests/HTMLRenderingTests.swift

While adding post editing I noticed that plain text always included trailing new line. This happened because `</p>` tag was always converted to a new line.
Fix makes it so the trailing `</p>` is skipped when converting to new lines.

Prevent trailing new line from being added to extracted post plain text

---

Sources/TootSDK/Models/Instance.swift
Sources/TootSDK/Models/NodeInfo.swift
Sources/TootSDK/Models/TootNotification.swift
Sources/TootSDK/Models/TootSDKFlavour.swift
Sources/TootSDK/TootClient/TootClient+Account.swift
Sources/TootSDK/TootClient/TootClient+Announcements.swift
Sources/TootSDK/TootClient/TootClient+Conversation.swift
Sources/TootSDK/TootClient/TootClient+FollowRequests.swift
Sources/TootSDK/TootClient/TootClient+Lists.swift
Sources/TootSDK/TootClient/TootClient+Notifications.swift
Sources/TootSDK/TootClient/TootClient+Post.swift
Sources/TootSDK/TootClient/TootClient+Suggestions.swift
Sources/TootSDK/TootClient/TootClient+Trends.swift
Tests/TootSDKTests/FlavourTests.swift

This allows end clients to distinguish between these flavours. In my case I need this do display different icons and instance suggestions.

Separate iceshrimp and catodon from firefish

---

Sources/TootSDK/TootClient/TootClient+Media.swift
Sources/TootSDK/TootClient/TootClient+Post.swift

The changes are tested by running live on account connected to pixey.org and venera.social instances.
For Friendica I've enabled post source endpoint as it is supported.
Pixelfed has more changes:
- Edit starts by concurrently updating media descriptions using separate endpoint since it is not possible to edit them using main endpoint.
- Content is sent as json instead of multipart
- Edited post is not returned from edit endpoint so it is requested manually
- Post source endpoint is marked as not supported

Post editing fixes

---

Sources/TootSDK/Models/Card.swift

Some recently added Mastodon features for link preview cards:
- article language
- publication date
- image description for article thumbnail
- authors array (in addition to the existing `author_name` and `author_url`) that can reference the author’s Fediverse account
These API additions are, as usual, missing from Mastodon’s documentation as far as I can tell, but were announced in [their blog post](https://blog.joinmastodon.org/2024/07/highlighting-journalism-on-mastodon/) and are live on mastodon.social. For example, [this post from the Verge](https://mastodon.social/@theverge_com/112887138012612832) has all of these properties, which you can test with this PR using `swiftyadmin get-post -u https://mastodon.social -i 112887138012612832 -t "[your_api_token]"`
All added properties are …

Add latest preview card attributes returned by Mastodon

---

Sources/TootSDK/Models/Card.swift

Whoops! I didn’t catch this before I submitted #297

Provide default value for `language` in `Card` initializer

---

Sources/TootSDK/TootClient/Streaming/StreamingClient.swift

Currently, if a streaming connection gets disconnected, StreamingClient will automatically retry even if the connection is idle (i.e. there are no subscribers to any streaming feeds). This PR makes the behavior in this case configurable, and by default does not automatically try to reconnect an unused connection.
The previous behavior of always retrying can be achieved by setting `retryIfNoSubscribers` to `true` on the StreamingClient instance.
In my client app, I’m leaving the websocket connection open after the user finishes using it (e.g. by leaving whatever view is subscribed to a streaming feed) and just unsubscribing from the feed. This makes it faster and use less resources to resubscribe, **but** if the connection goes down while it’s not being used, having it always automatically …

Add configurable behavior for retrying idle streaming connection

---

Sources/TootSDK/TootClient/TootClient+Search.swift

I broke out the mastodon flavor check if `excludeUnreviewed` is non-nil in `search()` into a TootFeature so API users can check to see if it’s supported using `TootClient.supportsFeature(.searchExcludeUnreviewed)` and adjust their behavior accordingly.

Add `TootFeature.searchExcludeUnreviewed`

---

Package.swift
Sources/TootSDK/Models/Streaming/StreamingEvent.swift
Sources/TootSDK/Models/TootSDKError.swift
Sources/TootSDK/TootClient/TootClient+Streaming.swift
Tests/TootSDKTests/Resources/streaming_error.json
Tests/TootSDKTests/StreamingTests.swift

This PR adds some improvements in relation to #304:
- Extends debugOn() from TootClient so event payloads may be printed in console
- Adds support for handling server sent errors as events. For now it simply gets retrown as a `TootSDKError.unexpectedError` with the server message as a description

Fix: Use preferred clientName for web socket connections, debugOn() now also prints raw socket events

---

Sources/TootSDK/Models/Streaming/StreamingTimeline.swift

Fixes #304 - the rawValue of the .userNotification timeline was `userNotification` when it should have been `user:notification`

Fix rawValue of user notification timeline

---

Sources/TootSDK/TootClient/TootClient.swift

Was still hardcoded, clientName only used in fetch.

Properly set clientName in user-agent of fetch

---

Examples/swiftyadmin/Sources/swiftyadmin/Posts/GetPost.swift
Sources/TootSDK/TootClient/TootClient+Streaming.swift
Sources/TootSDK/TootClient/TootClient.swift

This PR fixes #312 
It is now possible to configure a custom value for the user agent header as [described in the spec](https://developer.mozilla.org/en-US/docs/Glossary/User_agent).
For example:
```
let client = try await TootClient(
connect: URL(string: url)!,
clientName: "SwiftyAdminExample",
accessToken: token,
httpUserAgent: "SwiftyAdminExample 0.0")
```
When httpUserAgent is not set, it will have the value of clientName.

Add httpUserAgent field setting outgoing User-Agent header

---

Sources/TootSDK/Models/TootNotification.swift
Tests/TootSDKTests/TootNotificationParamsTests.swift

Adds emoji reaction notification type that might be sent by Sharkey.
Additionally, since this is a second time where someone reported non-working notifications due to a missing notification type, I decided to add dedicated case for unknown types. This way list of notifications will decode correctly giving clients chance to handle unknown cases in a better way. (Like displaying message to user to report that problem.)

Add emoji reaction and unknown notification types

---

Package.swift
Sources/TootSDK/Models/Relationship.swift
Sources/TootSDK/TootClient/TootClient+Relationships.swift
Tests/TootSDKTests/RelationshipTests.swift
Tests/TootSDKTests/Resources/relationship_sharkey.json

Sharkey returns smaller set of data than Mastodon when fetching user relationship. To properly decode its responses additional fields needed to be marked as optional.
I considered adding default values instead of optional but ultimately decided that it'll be better to leave that up to clients.

Fix user relationship endpoint for sharkey

---

Sources/TootSDK/Models/CreateAppRequest.swift
Sources/TootSDK/TootClient/TootClient+Request.swift
Sources/TootSDK/TootClient/TootClient.swift

Clients can provide a URL to their website, which is the link when pressing on the client name in the details of a toot. (https://docs.joinmastodon.org/methods/apps/#form-data-parameters)
This PR exposes this parameter, which has been "" by default and still is the default, to the client.

Add optional parameter for client website

---

Sources/TootSDK/Models/Instance/Instance.swift
Sources/TootSDK/Models/Instance/InstanceConfiguration.swift
Sources/TootSDK/Models/Instance/InstanceV1.swift
Sources/TootSDK/Models/Instance/InstanceV2.swift
Sources/TootSDK/TootClient/TootClient+Streaming.swift

Somehow I missed that the instance v2 API uses a different property name for the streaming URL. The result was that you couldn’t start streaming if TootSDK used v2 to get the instance info. This fixes that by using a separate type for the URLs struct for v1 and v2. That means this fix is a breaking change.
For consistency, I also replaced the `Instance` protocol’s `urls` property with a `streamingURL` property that returns the appropriate value from either version, and in v2 I added Mastodon's undocumented `status` property that returns the URL of the server status page.

Fix configuration.urls not working with the Instance v2 API

---

.github/workflows/build.yml
.github/workflows/build_examples.yml

This PR adopts the `macos-15` build image which comes preinstalled with Xcode 16.0.
This will enable tests to be written using the new Swift Testing framework and addresses the build errors from #323

[BREAKING] Add support for Xcode 16, it is no longer possible to run tests on Xcode 15

---

Sources/TootSDK/HTMLRendering/AttributedString+Util.swift
Sources/TootSDK/HTMLRendering/AttributedStringRenderer.swift
Sources/TootSDK/Models/ParsedContent.swift
Tests/TootSDKTests/AttributedStringRendererTests.swift
Tests/TootSDKTests/Helpers/XCTestCase+LocalContent.swift

This is a replacement renderer for `UIKitAttribStringRenderer` and `AppKitAttribStringRenderer` that uses newer `AttributedString` API. 
Changes from old renderers:
- Fixed bold and italic styles
- Added styling of headings
- Improved how new lines are added between paragraphs and inline elements
- Plain string now has consistent new lines with attributed string
- Nested lists have increased indent
- Emojis are ignored for now
This is an initial version that should be good for most of the cases. I'm looking for feedback if anyone decides to use it and encounters posts that would render incorrectly.
Here is an example of a [markdown formatted post](https://poa.st/@pipilo/posts/Ano93ccHOUVMJPq0h6) from pleroma as it appears in my app using this renderer:

Attributed string renderer

---

Package.swift
Sources/TootSDK/Extensions/Decoding+Helpers.swift
Sources/TootSDK/Models/Card.swift
Sources/TootSDK/TootClient/TootClient+Relationships.swift
Tests/TootSDKTests/CardTests.swift
Tests/TootSDKTests/DecodingTests.swift
Tests/TootSDKTests/Resources/card_string_size.json

[Fix error when trying to follow account without extra params](https://github.com/TootSDK/TootSDK/commit/f8d5b75f47ab55e70e0b39150769c7bfed0f5795)
[Fix decoding of card with width/height as string instead of int](https://github.com/TootSDK/TootSDK/commit/67880f5eeb8db42f9ff34dc563316a87dfbde618)

Pleroma fixes

---

Examples/swiftyadmin/Sources/swiftyadmin/Account/GetPreferences.swift
Examples/swiftyadmin/Sources/swiftyadmin/swiftyadmin.swift
Sources/TootSDK/Models/Preferences.swift
Sources/TootSDK/TootClient/TootClient+Account.swift

1. Added Mastodon’s “autoplay gifs” setting to `Preferences` (see mastodon/mastodon#22706 - there’s currently only a way to read this setting but not write it, so its usefulness for clients is questionable, but it still seems important to include since it’s accessibility-related)
2. Added a TootClient method to get the Preferences (I didn’t see an existing method for this)
3. Added `get-preferences` subcommand to swiftyadmin for testing this functionality.

Get account preferences and gif autoplay setting

---

Sources/TootSDK/HTTP/PagedResult.swift
Sources/TootSDK/HTTP/Pagination.swift
Sources/TootSDK/TootClient/TootClient+DomainBlocks.swift
Sources/TootSDK/TootClient/TootClient.swift
Sources/TootSDK/TootStream/TootStream+Posts.swift
Tests/TootSDKTests/PaginationTests.swift

Closes #326 
Fixes incorrect pagination identifiers if there are duplicate parameters in next and prev links.
For compatibility `info` in `PagedResult` is filled with assumption that ids will be in specific places, and `nextPage` with `previousPage` are initialized as inverted variants of next/prev links.

Fix broken pagination if links share the same parameter names

---

Sources/TootSDK/Models/ScheduledPostRequest.swift
Sources/TootSDK/Models/TootSDKError.swift
Sources/TootSDK/TootClient/TootClient+Reports.swift
Tests/TootSDKTests/ScheduledPostTests.swift

Fixes #334 
As [discussed on the 'don](https://toot.iamkonstantin.eu/@konstantin/113996972469397165), hope that helps!

Add `reason` parameter to `TootSDKError.invalidParameter`

---

Sources/TootSDK/Models/MediaAttachment.swift

- `previewRemoteUrl` property on `MediaAttachment`
- from mastodon/mastodon#14358
- `colors` metadata used in Mastodon to theme the player for audio attachments using colors extracted from the artwork
- from mastodon/mastodon#14209

Add missing MediaAttachment properties

---

Package.swift
Sources/TootSDK/HTTP/Decoder.swift
Tests/TootSDKTests/MarkerTests.swift
Tests/TootSDKTests/Resources/markers_unix_timestamp.json

This is a fix for instances on https://gblog4.popolon.org/snac/, which appears to be formatting marker update dates as unix timestamp.

Decode dates formatted as unix timestamp

---

Sources/TootSDK/Models/Preferences.swift

Previously, calling `TootClient.getPreferences()` would throw an error if the user had their Mastodon media setting set to “show all” or “hide all”. The API returns the strings `hide_all` or `show_all`, but TootSDK expected `hideAll` or `showAll`

Fix `ExpandMedia` expecting camel case when the Mastodon API returns snake case

---

Sources/TootSDK/Models/Filter.swift

This was added in Mastodon 4.4.0 (Mastodon API version 5); see Mastodon/Mastodon#34256
Pending a solution for #343, clients must update ASAP with this fix to avoid errors when making a wide range of API calls if the user has set up any filters with the new option on Mastodon servers running nightlies (e.g. mastodon.social).

Add “blur” filter action

---

Examples/swiftyadmin/Sources/swiftyadmin/Account/RegisterAccount.swift
Examples/swiftyadmin/Sources/swiftyadmin/Instance/GetLanguages.swift
Examples/swiftyadmin/Sources/swiftyadmin/swiftyadmin.swift
Sources/TootSDK/HTTP/Encoder.swift
Sources/TootSDK/Models/Instance/InstanceConfiguration.swift
Sources/TootSDK/Models/Instance/InstanceLanguage.swift
Sources/TootSDK/Models/Instance/InstanceV2.swift
Sources/TootSDK/Models/RegisterAccountParams.swift
Sources/TootSDK/TootClient/TootClient+Instance.swift

Support Mastodon Instance additions

---

Sources/TootSDK/Models/DomainBlock.swift
Sources/TootSDK/Models/Instance/InstanceDomainBlock.swift
Sources/TootSDK/TootClient/TootClient+Instance.swift

Adds support for `api/v1/instance/peers` (list of connected servers) and `api/v1/instance/domain_blocks` (publicly viewable list of moderated servers).
I called the new struct `InstanceDomainBlock` because TootSDK already used `DomainBlock` for what Mastodon calls `Admin:DomainBlock`. Let me know if you’d rather shuffle the names around to match those used by the Mastodon documentation (i.e. rename TootSDK’s existing `DomainBlock` to `AdminDomainBlock` and the new `InstanceDomainBlock` to just plain `DomainBlock`).

Add instance domain blocks and peers endpoints

---

Examples/swiftyadmin/Sources/swiftyadmin/Instance/GetTermsOfService.swift
Sources/TootSDK/Models/PrivacyPolicy.swift
Sources/TootSDK/Models/TermsOfService.swift
Sources/TootSDK/TootClient/TootClient+Instance.swift

Announced in https://blog.joinmastodon.org/2025/05/legal-features-updates/
`getTermsOfService()` now returns a `TermsOfService` struct instead of `PrivacyPolicy`. This is a breaking change from my previous PR #332 (but only for the terms of service endpoint, not the others) because Mastodon changed what the endpoint returns since then. There shouldn't be any servers in the wild that still return the `PrivacyPolicy` type because that was only ever in nightly builds and not an official release.

Support versioned/dated terms of service endpoint

---

Sources/TootSDK/Models/Instance/InstanceRule.swift

Also announced in https://blog.joinmastodon.org/2025/05/legal-features-updates/
I made `Translation` a nested type within `InstanceRule`, but let me know if you’d prefer a separate top-level type like `InstanceRuleTranslation` instead.

Support server rule translations

---

Sources/TootSDK/HTTP/OpenEnum.swift
Tests/TootSDKTests/DecodingTests.swift

Missed that `Marker.Timeline` conforms to `CodingKeyRepresentable` for proper decoding. Updated `OpenEnum` to also conform to it where needed.

Conform OpenEnum to CodingKeyRepresentable

---

Examples/swiftyadmin/Sources/swiftyadmin/Account/EndorseAccount.swift
Examples/swiftyadmin/Sources/swiftyadmin/Account/GetEndorsements.swift
Examples/swiftyadmin/Sources/swiftyadmin/Account/UnendorseAccount.swift
Examples/swiftyadmin/Sources/swiftyadmin/Account/VerifyCredentials.swift
Examples/swiftyadmin/Sources/swiftyadmin/swiftyadmin.swift
Sources/TootSDK/Models/TootSource.swift
Sources/TootSDK/Models/UpdateCredentialsParams.swift
Sources/TootSDK/TootClient/TootClient+Relationships.swift

- Calling updateCredentials with the `attributionDomains` property is only supported if the server supports Mastodon API version 3 or higher.
- The `endorse` and `unendorse` endpoints are intended to replace the older `pin` and `unpin` which are now deprecated in Mastodon 4.4. The docs don’t give an API version for this change, just the main Mastodon version number.
- Since TootClient doesn’t (currently) track the Mastodon API version or Mastodon version, I didn’t add a version check in any of these methods, I just noted the requirement and deprecation in the DocC comments of each method.
- The [Mastodon 4.4 for developers](https://blog.joinmastodon.org/2025/07/mastodon-4-4-for-devs/) post also notes new endpoints for featuring/unfeaturing hashtags, which seem to be near-duplicates of …

Support Mastodon 4.4 account management additions

---

Sources/TootSDK/TootClient/TootClient+Media.swift
Sources/TootSDK/TootClient/TootClient+Post.swift

- Adds `deleteMedia(id:)` method that calls the [delete media endpoint](https://docs.joinmastodon.org/methods/media/#delete) added in Mastodon 4.4
- Adds optional `deleteMedia` parameter to `deletePost(id:)` method
As with the changes in #356, I noted the API version requirement in the DocC documentation.

Masto 4.4 media deletion

---

CLAUDE.md
Sources/TootSDK/Models/TootResponse.swift
Sources/TootSDK/TootClient/TootClient+Account.swift
Sources/TootSDK/TootClient/TootClient+Announcements.swift
Sources/TootSDK/TootClient/TootClient+Conversation.swift
Sources/TootSDK/TootClient/TootClient+DomainBlocks.swift
Sources/TootSDK/TootClient/TootClient+FeaturedTags.swift
Sources/TootSDK/TootClient/TootClient+Filters.swift
Sources/TootSDK/TootClient/TootClient+FollowRequests.swift
Sources/TootSDK/TootClient/TootClient+Instance.swift
Sources/TootSDK/TootClient/TootClient+Lists.swift
Sources/TootSDK/TootClient/TootClient+Markers.swift
Sources/TootSDK/TootClient/TootClient+Media.swift
Sources/TootSDK/TootClient/TootClient+Notifications.swift
Sources/TootSDK/TootClient/TootClient+OauthApps.swift
Sources/TootSDK/TootClient/TootClient+Poll.swift
Sources/TootSDK/TootClient/TootClient+Post.swift
Sources/TootSDK/TootClient/TootClient+ProfileDirectory.swift
Sources/TootSDK/TootClient/TootClient+Search.swift
Sources/TootSDK/TootClient/TootClient+Suggestions.swift
Sources/TootSDK/TootClient/TootClient+Tags.swift
Sources/TootSDK/TootClient/TootClient+TimeLine.swift
Sources/TootSDK/TootClient/TootClient+Trends.swift
Sources/TootSDK/TootClient/TootClient.swift
Tests/TootSDKTests/TootResponseTests.swift

This PR fixes #331 by exposing HTTP response headers and metadata from TootSDK API calls while maintaining backward compatibility. 
Create a new generic wrapper type that contains:
- **data**: The decoded response data (existing return type)
- **headers**: HTTP response headers as `[String: String]`
- **statusCode**: HTTP status code
- **url**: Response URL
- **rawBody**: Raw response body as `Data` (for debugging/fallback)
- **Existing method signatures remain unchanged** - No breaking changes to current API
- **Implementation migration** - Current method implementations will be moved to new `*Raw()` methods
- **Delegation pattern** - Existing methods will be refactored to call Raw methods and extract only the data property
For each existing method like `getLists()`, add:
- …

Expose HTTP response headers from API calls

---

Package.swift
Sources/TootSDK/Models/Quote.swift
Tests/TootSDKTests/QuoteTests.swift
Tests/TootSDKTests/Resources/post_akkoma_quote.json

This fixes the issue @technicat pointed out in #355 where post parsing would fail for Akkoma quote posts. Now if parsing as a `Quote` fails, it tries to parse it as a `Post` as a fallback, then packages it as a TootSDK `Quote` struct.
Breaking because `Quote.state` is now optional (left as `nil` for Akkoma and other flavors that put a `Post` directly in the `Quote` property).
For the test json, I used the example that @technicat linked to: https://codeberg.org/technicat/fedicat/src/branch/main/Tests/TootSDKTests/Resources/post_akkoma_quote.json

Fix error parsing quote posts from Akkoma

---

Examples/SharingGRDBExample/SharingGRDBExample.xcodeproj/project.pbxproj
Examples/SharingGRDBExample/SharingGRDBExample.xcodeproj/project.xcworkspace/contents.xcworkspacedata
Examples/SharingGRDBExample/SharingGRDBExample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Examples/SharingGRDBExample/SharingGRDBExample.xcodeproj/xcshareddata/xcschemes/TootSDKExample.xcscheme
Examples/SharingGRDBExample/SharingGRDBExample/Assets.xcassets/AccentColor.colorset/Contents.json
Examples/SharingGRDBExample/SharingGRDBExample/Assets.xcassets/AppIcon.appiconset/Contents.json
Examples/SharingGRDBExample/SharingGRDBExample/Assets.xcassets/Contents.json
Examples/SharingGRDBExample/SharingGRDBExample/Info.plist
Examples/SharingGRDBExample/SharingGRDBExample/Models/Schema.swift
Examples/SharingGRDBExample/SharingGRDBExample/TootSDKExampleApp.swift
Examples/SharingGRDBExample/SharingGRDBExample/Views/RootView.swift

This adds a basic example of a macOS gui app using `PointFree's SharingGRDB`. These are the changes:
- Removed all `SwiftData` related code
- Added [SharingGRDB](https://github.com/pointfreeco/sharing-grdb) framework to the package dependencies
- Reduced the macOS target to 15.0 (not on the latest version yet ;))
- Added `Models/Schema.swift` with the code to create the necessary tables & the database connection
- Adapted `Views/RootView.swift` to use `SharingGRDB` instead.
- Renamed some targets to reflect the new name.
All the code is in the `Examples/SharingGRDBExample` directory. Let me know if you have questions or if I need to change anything!

Added an example of a TootSDK graphical client using SharingGRDB

---

Examples/swiftyadmin/Package.resolved
Examples/swiftyadmin/Sources/swiftyadmin/OauthApps/DeleteOauthApp.swift
Examples/swiftyadmin/Sources/swiftyadmin/OauthApps/ListOauthApps.swift
README.md
Sources/TootSDK/Models/ServerConfiguration.swift
Sources/TootSDK/TootClient/TootClient.swift
Tests/TootSDKTests/EncodingTests.swift
Tests/TootSDKTests/FeatureTests.swift
Tests/TootSDKTests/ServerConfigurationTests.swift
Tests/TootSDKTests/TootNotificationParamsTests.swift

This PR fixes #365 by allowing apps to cache (and restore) TootClient without having to call `connect()` (cf. also mentioned in https://github.com/TootSDK/TootSDK/pull/361#discussion_r2265223662)
Example
```swift
// Save configuration
let config = client.serverConfiguration
let data = try JSONEncoder().encode(config)
// Restore later
let savedConfig = try JSONDecoder().decode(ServerConfiguration.self, from: data)
let restoredClient = TootClient(
instanceURL: url,
serverConfiguration: savedConfig
)
```

[BREAKING] Allow caching and restoring TootClient without calling connect()

---

Sources/TootSDK/Models/PushSubscriptionParams.swift
Sources/TootSDK/TootClient/TootClient+Notifications.swift
Sources/TootSDK/WebPushEncryption/WebPushMessageEncryption.swift
Tests/TootSDKTests/WebPushMessageEncryptionTests.swift

In order to correctly add support for GoToSocial push notifications we need a way to decode them using AES-128-GCM encoding which is what they are using. This pull request addresses that by updating the existing decrypt(andDecode) methods with a new `ContentEncoding` parameter. This is a breaking change.
Additionally Mastodon also implemented webpush using the same encoding but it is opt-in. A way to enable that is by passing `subscription[standard]` set to true when creating push subscription. I implemented that with a new optional parameter on `Subscription` struct and a feature telling whether it's available or not. 
Reference:
- https://github.com/feditext/feditext/commit/87b4075c58de319dd556223745a3069a686c2e27
- https://datatracker.ietf.org/doc/html/rfc8291#section-5
- …

AES-128-GCM encoding support for webpush messages

---

Sources/TootSDK/HTTP/PagedResult.swift

As I was adding pagination tests to my current project, I wanted to use `PagedResult` directly.
Sadly there was no public init for it, so swiftc was complaining.
- this adds the missing public init for `PagedResult` only
- no new test were added as this make the structure public only, no feature was changed
- existing tests all passed

add public init for PagedResult for better testability
