Examples/swiftui-toot/TootSDK-Demo/TootManager.swift, Examples/swiftui-toot/TootSDK-Demo/Views/Feed/FeedSelectionView.swift, Sources/TootSDK/HTTP/PagedInfo.swift, Sources/TootSDK/Models/Account.swift, Sources/TootSDK/Models/AccountLookup.swift, Sources/TootSDK/Models/Attachment.swift, Sources/TootSDK/Models/Context.swift, Sources/TootSDK/Models/CreatePoll.swift, Sources/TootSDK/Models/EditPostParams.swift, Sources/TootSDK/Models/Emoji.swift, Sources/TootSDK/Models/FollowAccountParams.swift, Sources/TootSDK/Models/MediaAttachment.swift, Sources/TootSDK/Models/MuteAccountParams.swift, Sources/TootSDK/Models/Poll.swift, Sources/TootSDK/Models/Post.swift, Sources/TootSDK/Models/PostEdit.swift, Sources/TootSDK/Models/PostParams.swift, Sources/TootSDK/Models/PostSource.swift, Sources/TootSDK/Models/Relationship.swift, Sources/TootSDK/Models/ScheduledPost.swift, Sources/TootSDK/Models/ScheduledPostParams.swift, Sources/TootSDK/Models/Search.swift, Sources/TootSDK/Models/SearchParams.swift, Sources/TootSDK/Models/Tag.swift, Sources/TootSDK/Models/TagHistory.swift, Sources/TootSDK/Models/TootField.swift, Sources/TootSDK/Models/TootSource.swift, Sources/TootSDK/Models/UploadMediaAttachmentParams.swift, Sources/TootSDK/TootClient/TootClient.swift, Sources/TootSDK/TootStream.swift
This fixes the sendable warnings invoked with Xcode 14.3.
It's entirely possible I've missed some with this PR, and would definitely appreciate some 👀 !
=> Fix sendable warnings for Xcode 14.3 (beta)

Sources/TootSDK/Models/PostEdit.swift
pos] -> post
revisionå -> revision
=> fixed comment typos in PostEdit.swift

Sources/TootSDK/Models/Timeline/Timeline.swift, Sources/TootSDK/Models/Timeline/UserTimelineQuery.swift, Sources/TootSDK/TootClient/TootClient+Account.swift, Sources/TootSDK/TootClient/TootClient+TimeLine.swift
https://api.pleroma.social/#operation/AccountController.statuses
https://docs.joinmastodon.org/methods/accounts/#statuses
=> User posts timeline

Examples/swiftyadmin/Sources/swiftyadmin/Account/GetFeaturedTags.swift, Examples/swiftyadmin/Sources/swiftyadmin/swiftyadmin.swift, Sources/TootSDK/Extensions/Decoding+Helpers.swift, Sources/TootSDK/Models/FeaturedTag.swift, Sources/TootSDK/TootClient/TootClient+Account.swift, Tests/TootSDKTests/DecodingTests.swift
https://docs.joinmastodon.org/methods/accounts/#featured_tags
=> User featured tags

Sources/TootSDK/Models/Instance.swift
=> Fix Instance doesn't parse for pixelfed

Examples/swiftui-toot/SwiftUI-Toot.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Sources/TootSDK/TootClient/TootClient+Account.swift
This fixes our linter warnings, and also updates SwiftNIO
=> Fix Linter

README.md
=> Fix - Example links in README.md

Sources/TootSDK/Models/Report.swift, Sources/TootSDK/Models/ScheduledPost.swift
missed these two in the previous PR
https://github.com/TootSDK/TootSDK/pull/110
=> Report and ScheduledPost implement Identifiable

Sources/TootSDK/HTTP/URLSession+asyncData.swift
=> feat: improve async implementation for data task

Examples/tootsdk-release/Package.resolved, Examples/tootsdk-release/Sources/tootsdk-release/Posts/MakePost.swift
hardcoded the handle for GitHub API does not return the correct value
=> Fix release notes not tagging me correctly 😇

Sources/TootSDK/TootClient/TootClient+Tags.swift
Added TootClient.getFollowedTags() to TootClient+Tags.swift
https://docs.joinmastodon.org/methods/followed_tags/
=> added followed_tags access

Examples/swiftyadmin/Package.resolved, Examples/swiftyadmin/README.md, Examples/swiftyadmin/Sources/swiftyadmin/Notifications/ListAllNotifications.swift, Examples/swiftyadmin/Sources/swiftyadmin/swiftyadmin.swift, Examples/vaportoot/Package.resolved, README.md, Sources/TootSDK/HTTP/PagedResult.swift, Sources/TootSDK/Models/TootNotification.swift, Sources/TootSDK/Models/TootNotificationParams.swift, Sources/TootSDK/TootClient/TootClient+Notifications.swift, Sources/TootSDK/TootClient/TootClient+Tags.swift
* Adds support for managing notifications
* Adds hasPrevious, hasNext, previousPage and nextPage to PaginatedResult
* Some docs improvements
=> List and dismiss notifications, improve pagination and docs

Examples/swiftui-toot/SwiftUI-Toot.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Package.resolved, Sources/TootSDK/TootClient/TootClient+Relationships.swift
API: added access to Mastodon API blocks and mutes
swiftlint: removed extra newline
packages: updated to latest in main and swiftui example
=> added getBlockedAcccounts, getMutedAcounts, lint fix, package updates

Sources/TootSDK/Models/TootNotification.swift
Taken  from https://docs.joinmastodon.org/entities/Notification/#type
=> added comment doc for TootNotification update type

Sources/TootSDK/Models/Suggestion.swift, Sources/TootSDK/TootClient/TootClient+Suggestions.swift
TootClient.getSuggestions() performs this query
https://docs.joinmastodon.org/methods/suggestions/
=> feat: view follow suggestions

Sources/TootSDK/Models/SearchAccountsParams.swift, Sources/TootSDK/TootClient/TootClient+Account.swift
https://docs.joinmastodon.org/methods/accounts/#search
=> Search accounts endpoint

Examples/tootsdk-release/Sources/tootsdk-release/Posts/MakePost.swift, Examples/tootsdk-release/Sources/tootsdk-release/tootsdk-release.swift, Package.swift, Sources/TootSDK/Models/FeatureTagParams.swift, Sources/TootSDK/Models/UpdateCredentialsParams.swift, Sources/TootSDK/PrivacyInfo.xcprivacy, Sources/TootSDK/TootClient/TootClient+Account.swift, Sources/TootSDK/TootClient/TootClient+FeaturedTags.swift, Sources/TootSDK/TootClient/TootClient+ScheduledPost.swift
- Adds privacy manifest
- Removes hardcoded user id from the post automation (my profile link now resolves from GitHub)
- Reformats source files
=> Add privacy manifest

Package.swift, Sources/TootSDK/TootClient/TootClient+Account.swift, Sources/TootSDK/TootClient/TootClient+Lists.swift, Tests/TootSDKTests/ListTests.swift, Tests/TootSDKTests/Resources/list.json
=> added TootClient.getLists(id) to get lists an account is in

.swiftlint.yml, Sources/TootSDK/TootClient/TootClient+Account.swift, Sources/TootSDK/TootClient/TootClient+Lists.swift, Sources/TootSDK/TootClient/TootClient+Relationships.swift
This improves the getList implementation from #185 with a name that better describes its function and also gets moved to the Account related methods.
=> fix: rename getLists to getListsContainingAccount

Sources/TootSDK/TootClient/TootClient+Lists.swift
Lists are not available on Pixelfed and always return empty response.
https://github.com/pixelfed/pixelfed/blob/e36d7da8413e700edcd9b639db7c44b2b97394fc/app/Http/Controllers/Api/ApiV1Controller.php#L1558
=> Add lists feature

Examples/swiftyadmin/Sources/swiftyadmin/Instance/GetInstance.swift, Examples/swiftyadmin/Sources/swiftyadmin/swiftyadmin.swift, Sources/TootSDK/Models/Instance.swift
https://docs.joinmastodon.org/entities/V1_Instance/#configuration
Tested for 
- https://mastodon.world
- https://pxlmo.com
- https://poa.st
- https://venera.social
- https://blob.cat
=> Parse instance configuration from instance info request

Sources/TootSDK/Models/Announcement.swift, Sources/TootSDK/Models/AnnouncementParams.swift, Sources/TootSDK/Models/PixelfedReportParams.swift, Sources/TootSDK/Models/Poll.swift, Sources/TootSDK/Models/ReportCategory.swift, Sources/TootSDK/Models/ReportParams.swift, Sources/TootSDK/TootClient/TootClient+Announcements.swift, Sources/TootSDK/TootClient/TootClient+Instance.swift, Sources/TootSDK/TootClient/TootClient+Reports.swift
https://docs.joinmastodon.org/methods/announcements/
=> support for reading announcements and marking an announcement as read

Examples/swiftyadmin/Sources/swiftyadmin/Markers/GetMarkers.swift, Examples/swiftyadmin/Sources/swiftyadmin/Markers/UpdateMarkers.swift, Examples/swiftyadmin/Sources/swiftyadmin/swiftyadmin.swift, Sources/TootSDK/Models/Marker.swift, Sources/TootSDK/TootClient/TootClient+Markers.swift
Marked as not available for:
- firefish: returns 404.
- pixelfed: both endpoints always return empty array for me which doesn't decode.
=> Add support for markers API

Sources/TootSDK/Models/Filter.swift, Sources/TootSDK/Models/FilterResult.swift, Sources/TootSDK/Models/Post.swift
https://docs.joinmastodon.org/entities/Status/#filtered
=> add support for recognizing a post that should be filtered (i.e. filtered with warning)

Sources/TootSDK/Models/Instance.swift
need to take in account auto snakeCase conversion, status_count -> statusCount
=> fix: nil Instance.postsCount

Sources/TootSDK/TootClient/TootClient+ScheduledPost.swift
Fixes #225 
Note: This PR is based on #227
=> Deprecate get scheduled post

Sources/TootSDK/TootClient/TootClient+FollowRequests.swift
=> Add pagination to get follow requests

Examples/swiftui-toot/SwiftUI-Toot.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Package.resolved, Package.swift, Sources/TootSDK/HTTP/Data+prettyPrintedJSONString.swift, Sources/TootSDK/Models/Instance.swift, Sources/TootSDK/Models/TootSDKFlavour.swift, Sources/TootSDK/TootClient/TootClient+Account.swift, Sources/TootSDK/TootClient/TootClient+Announcements.swift, Sources/TootSDK/TootClient/TootClient+Conversation.swift, Sources/TootSDK/TootClient/TootClient+DomainBlocks.swift, Sources/TootSDK/TootClient/TootClient+FollowRequests.swift, Sources/TootSDK/TootClient/TootClient+Lists.swift, Sources/TootSDK/TootClient/TootClient+Suggestions.swift, Sources/TootSDK/TootClient/TootClient+Trends.swift, Tests/TootSDKTests/FlavourTests.swift, Tests/TootSDKTests/Resources/instance_akkoma.json, Tests/TootSDKTests/Resources/instance_firefish_contact_removed.json, Tests/TootSDKTests/Resources/instance_iceshrimp_contact_removed.json, Tests/TootSDKTests/Resources/instance_sharkey_contact_removed.json
For now, recognize iceshrimp as firefish, same as catodon (both firefish forks). Sharkey is a misskey fork but separate from firefish.
Split the trends feature into separate features for trending posts/tags/links. Firefish only supports trending posts, and sharkey only supports trending tags.
=> flavour check for sharkey and iceshrimp

Makefile, Tests/TootSDKTests/AccountTests.swift, Tests/TootSDKTests/ActivityTests.swift, Tests/TootSDKTests/AttribStringRendererTests.swift, Tests/TootSDKTests/DecodingTests.swift, Tests/TootSDKTests/FamiliarFollowersTests.swift, Tests/TootSDKTests/FeatureTests.swift, Tests/TootSDKTests/FlavourTests.swift, Tests/TootSDKTests/Helpers/XCTestCase+LocalContent.swift, Tests/TootSDKTests/InstanceTests.swift, Tests/TootSDKTests/ListTests.swift, Tests/TootSDKTests/PaginationTests.swift, Tests/TootSDKTests/PostTests.swift, Tests/TootSDKTests/RelationshipTests.swift, Tests/TootSDKTests/SearchTests.swift, Tests/TootSDKTests/TagTests.swift, Tests/TootSDKTests/TootNotificationParamsTests.swift, Tests/TootSDKTests/WebPushMessageEncryptionTests.swift
=> Format & Lint should cover unit tests as well

CONTRIBUTING.md, Tests/TootSDKTests/PostTranslationTests.swift, Tests/TootSDKTests/ScheduledPostTests.swift
Some cleanup and updates to CONTRIBUTING to bring it up to the date with current way of linting.
There are still some improvements we can do currently opened as issues.
=> Cleanup and update CONTRIBUTING

CONTRIBUTING.md
This is to cover several issues:
- https://github.com/TootSDK/TootSDK/issues/258
- https://github.com/TootSDK/TootSDK/issues/256
- https://github.com/TootSDK/TootSDK/issues/255
- https://github.com/TootSDK/TootSDK/issues/254
=> Update - contributing.md

Examples/swiftyadmin/Sources/swiftyadmin/Logout.swift, Examples/swiftyadmin/Sources/swiftyadmin/swiftyadmin.swift, Sources/TootSDK/TootClient/TootClient+Account.swift
fixes #264
SwiftyAdmin extended with an example
=> Adds a way for apps to logout by invalidating their token

Sources/TootSDK/TootClient/TootClient+Account.swift
Added in Mastodon 4.2.0
https://docs.joinmastodon.org/methods/profile/
=> added TootClient.deleteProfileAvatar() and TootClient.deleteProfileHeader()

Package.swift, Sources/TootSDK/Models/Post.swift, Tests/TootSDKTests/PostEditedTests.swift, Tests/TootSDKTests/Resources/post_edited.json
Adds the [edited_at](https://docs.joinmastodon.org/entities/Status/#edited_at) field as proposed in #277 
Thanks @technicat 🎊
=> Adds Post.editedAt, introduced in Mastodon 4.2

README.md
I’ve made a Mastodon client for Apple Watch/watchOS using TootSDK!
Thanks for making such an awesome library!
=> Add Oxpecker to list of apps using TootSDK

Package.resolved, Package.swift
=> fix(#283): fix build when compiling with swift 6

Examples/swiftyadmin/Package.resolved, Examples/swiftyadmin/Sources/swiftyadmin/Filters/CreateFilter.swift, Examples/swiftyadmin/Sources/swiftyadmin/Filters/GetFilters.swift, Examples/swiftyadmin/Sources/swiftyadmin/Filters/UpdateFilter.swift, Examples/swiftyadmin/Sources/swiftyadmin/swiftyadmin.swift, Sources/TootSDK/Models/CreateFilterParams.swift, Sources/TootSDK/Models/Filter.swift, Sources/TootSDK/Models/UpdateFilterParams.swift, Sources/TootSDK/TootClient/TootClient+Filters.swift, Tests/TootSDKTests/FilterTests.swift
Ready for review.
Tested only via command line for now. I'll remove Draft once fully implemented and tested in my app in case I discover anything.
=> Adds support for creating and updating filters

Examples/swiftyadmin/README.md, Package.swift, Sources/TootSDK/Models/Card.swift, Sources/TootSDK/Models/Instance.swift, Tests/TootSDKTests/FlavourTests.swift, Tests/TootSDKTests/InstanceTests.swift, Tests/TootSDKTests/Resources/instance_pixelfed.json
=> Work around for pixelfed get instance info

Sources/TootSDK/Models/Streaming/StreamingEvent.swift, Sources/TootSDK/Models/TootSDKError.swift
Check the streaming event for error/status fields and decode those.
=> Add streaming error

Sources/TootSDK/TootClient/TootClient+Post.swift
=> Fix post submission using sharkey

Sources/TootSDK/Models/TootNotification.swift, Tests/TootSDKTests/CardTests.swift, Tests/TootSDKTests/TootNotificationParamsTests.swift
New notification type added in https://github.com/mastodon/mastodon/pull/32709
=> Add notification annual_report type

.github/workflows/lint.yml
This PR fixes #335 and ublocks all open PRs.
=> Fix CI: Update setup-swift action to v2

.github/workflows/lint.yml, Package.resolved, Sources/MultipartKitTootSDK/MultipartParser.swift, Tests/TootSDKTests/ScheduledPostTests.swift, Tests/TootSDKTests/TootNotificationParamsTests.swift
Workaround for failing lint job https://github.com/swift-actions/setup-swift/issues/694#issuecomment-2850885210
=> Fix pipeline by removing failing setup-swift action

Sources/TootSDK/TootClient/TootClient+Filters.swift
https://docs.joinmastodon.org/methods/filters/#create
=> Feature for filter blur action

Tests/TootSDKTests/Resources/account_pixelfed.json, Tests/TootSDKTests/Resources/featured_tag.json, Tests/TootSDKTests/Resources/featured_tag_unused.json, Tests/TootSDKTests/Resources/post no emojis.json, Tests/TootSDKTests/Resources/post with emojis and attachments.json, Tests/TootSDKTests/Resources/post wordle linebreaks.json, Tests/TootSDKTests/Resources/scheduled_post_attachment.json, Tests/TootSDKTests/Resources/scheduled_post_multiple_attachments.json, Tests/TootSDKTests/Resources/tag.json
This PR fixes #250
(long overdue, thanks @technicat)
=> fix: incorrectly escaped urls in test files

.github/workflows/build.yml, .github/workflows/build_examples.yml, .github/workflows/lint.yml, .github/workflows/release-update.yml, Sources/MultipartKitTootSDK/MultipartFormData.swift, Sources/MultipartKitTootSDK/MultipartPart.swift, Sources/TootSDK/Models/Instance/InstanceV1.swift, Sources/TootSDK/Models/ReportCategory.swift, Sources/TootSDK/Models/TootSDKError.swift, Sources/TootSDK/WebPushEncryption/WebPushMessageEncryption.swift
This PR fixes #378 and also
- bumps the macOS version for CI builds to 26
=> Workflow should use macOS-26
